var exports = module.exports = {
    "must": {
        "ar": "يجب أن يكون محدد",
        "bg": "трябва да бъде посочено",
        "cs": "musí být specifikován",
        "da": "skal være angivet",
        "de": "angegeben?",
        "en": "must be specified",
        "de_at": "angegeben?",
        "de_campers": "angegeben?",
        "de_ch": "angegeben?",
        "ee": "on kohustuslik",
        "el": "πρέπει να διευκρινιστεί",
        "en_sg": "must be specified",
        "en_vans": "must be specified",
        "es": "debe ser especificado",
        "es_ct": "ha de ser especificat",
        "es_vans": "debe ser especificada",
        "fi": "on mainittava",
        "fr": "doit être précisé",
        "he": "שדה זה הינו חובה",
        "hr": "mora biti specificirano",
        "hr_rs": "mora da bude specifikovano",
        "hu": "kötelezően kitöltendő",
        "in_id": "harus spesifik",
        "is": "þarf að tilgreina",
        "it": "deve essere specificata",
        "jp": "をご入力ください。",
        "ko": "반드시 기재해야 합니다",
        "lt": "turi būti nurodyta",
        "lv": "jānorāda",
        "my": "mesti dinyatakan",
        "nl": "wilt u de auto ophalen?",
        "nl_be": "wilt u de auto ophalen?",
        "nl_campers": "moet worden vermeld",
        "no": "må spesifiseres",
        "ph": "ito ay kailangang isulat",
        "pl": "musi być podane",
        "pt": "deve ser especificado",
        "ro": "trebuie specificat",
        "rs": "mora da bude specifikovano",
        "ru": "должен быть указан",
        "uk": "повинен бути зазначений",
        "sk": "musí byť upresnené",
        "sl": "mora biti izrecno navedeno",
        "sv": "måste specificeras",
        "sw": "lazima ibainishwe",
        "th": "ต้องระบุ",
        "tr": "belirlenmesi gerekiyor",
        "vi": "phải được chỉ rõ",
        "zs": "请填写",
        "zh": "請填寫",
        "zh_tw": "請填寫"
    },
    "dropoff": {
        "ar": "موقع اعادة السيارة",
        "bg": "Местоположение за връщане",
        "cs": "místo odevzdání",
        "da": "Afleverings Sted",
        "de": "Rückgabestation",
        "en": "Drop off location",
        "de_at": "Rückgabestation",
        "de_campers": "Rückgabestation",
        "de_ch": "Rückgabestation",
        "ee": "Tagastuskoht",
        "el": "Τοποθεσία επιστροφής",
        "en_sg": "Dropoff Location",
        "en_vans": "Dropoff Location",
        "es": "Lugar de devolución",
        "es_ct": "lloc de devolució",
        "es_vans": "Lugar de devolución",
        "fi": "Palautussijainti",
        "fr": "Le lieu de restitution",
        "fr_ch_vola": "Veuillez spécifier l'endroit de restitution",
        "fr_vola": "Veuillez spécifier l'endroit de restitution",
        "he": "תחנת החזרה",
        "hr": "Lokacija povratka automobila",
        "hr_rs": "Lokacija povratka automobila",
        "hu": "Autóleadás helye",
        "in_id": "Tempat pengembalian",
        "is": "Skilastaður",
        "it": "Località di arrivo",
        "jp": "返却する場所",
        "ko": "반납지역",
        "lt": "Automobilio grąžinimo vieta",
        "lv": "Atgriešanas Vieta",
        "my": "Tempat Mengembali",
        "nl": "Locatie van afleveren",
        "nl_be": "Locatie van afleveren",
        "nl_campers": "Locatie van afleveren",
        "no": "Returnerings sted",
        "ph": "Lokasyon ng paghahatiran",
        "pl": "Lokalizacja Zwrotu",
        "pt": "Estação de devolução",
        "ro": "Locaţie Predare",
        "rs": "Lokacija povratka automobila",
        "ru": "Место возврата",
        "uk": "Місце повернення",
        "sk": "Oblasť vrátenia",
        "sl": "Lokacija vrnitve",
        "sv": "Returplats",
        "sw": "Mahali pa kurejesha gari",
        "th": "สถานที่คืนรถ",
        "tr": "İade Yeri",
        "vi": "Vị Trí Trả Xe",
        "zs": "还车地点",
        "zh": "還車地點",
        "zh_tw": "還車地點"
    },
    "hour": {
        "ar": "يجب أن يكون هناك ساعة على الأقل بين معاد الإستلام و معاد التسليم",
        "bg": "Трябва да има поне един час преди получаване и връщане на автомобила",
        "cs": "Mezi vyzvednutím a navrácením musí být alespoň 1 hodina rozdíl.",
        "da": "Der skal være mindst en time imellem afhentning og aflevering",
        "de": "Es muss mindestens eine Stunde zwischen Abholung und Rückgabe liegen",
        "en": "There must be at least one hour between pick up and drop off",
        "ee": "Võtmise ja tagastamise vahel peab olema vähemalt 1 tund",
        "el": "Απαιτείται τουλάχιστον μια ώρα διαφορά μεταξύ της παραλαβής και επιστροφής",
        "es": "Debe haber una hora como mínimo entre la recogida y la devolución",
        "es_ct": "Ha d’haver almenys una hora entre la recollida i la devolució",
        "fi": "Haku- ja palautusajassa tulee olla vähintään yksi tunti eroa",
        "fr": "Il doit y avoir au moins une heure entre la prise en charge et la restitution",
        "he": "חובה שיהיה מינימום של שעה בין אסיפה והחזרת הרכב",
        "hr": "Dozvolite najmanje jedan sat između preuyimanja i povratka automobila.a biti bare",
        "hr_rs": "Dozvolite najmanje jedan čas između preuzimanja i povratka automobila.",
        "hu": "Legalább 1 órás különbség kell hogy legyen a felvétel és a leadás között",
        "in_id": "Setidaknya harus ada jarak 1 jam antara pengambilan dan pengembalian.",
        "is": "Það þarf að vera minnst ein klukkustund milli afhendingar- og skilatíma",
        "it": "Ci deve essere almeno un’ora di differenza tra il ritiro e la riconsegna",
        "jp": "返却のお時間は貸し出しから１時間後以降に設定ください",
        "ko": "대여시간과 반납시간을 최소 1시간 이상으로 지정하셔야 합니다",
        "lt": "Privalo būti bent viena valanda skirtumas tarp automobilio paėmimo ir grąžinimo",
        "lv": "Ir jābūt vismaz 1 stundas starpībai starp saņemšanu un atgriešanu",
        "my": "Masa pengambilan kenderaan mestilah sekurang-kurangnya satu jam sebelum masa mengembali",
        "nl": "Er moet tenminste één uur verschil zitten tussen ophaal- en inlevertijd",
        "no": "Det må være minst en time imellom henting og levering",
        "ph": "Dapat ay may isang oras na pagitan mula sa pagsunddo at pag hatid",
        "pl": "Pomiędzy odbiorem a zwrotem auta musi być przynajmniej godzina różnicy",
        "pt": "Deve haver pelo menos uma hora entre o levantamento e devolução",
        "pt_rc_br": "Deve haver pelo menos uma hora entre a retirada e a devolução.",
        "ro": "Intre colectarea si predarea masinii, este nevoie de cel putin o ora",
        "rs": "Dozvolite najmanje jedan čas između preuzimanja i povratka automobila.",
        "ru": "Должно быть не менее одного часа между получением и возвратом автомобиля",
        "uk": "Завжди дайте собі хоча б одну годину перед тим як забирати автомобіль і 1 годину до моменту повернення",
        "sk": "Musí tam byť minimálne jedna hodina medzi vyzdvihovaním a odovzdavaním",
        "sl": "Med prevzemom in vrnitvijo mora miniti vsaj ena uro",
        "sv": "Det måste vara minst en timma mellan upphämtnings- och avlämningstiden",
        "sw": "Lazima kuwe na angalau saa moja katika ya kuchukua na kurejesha gari",
        "th": "ระยะเวลารับและคืนรถจะต้องห่างกันอย่างต่ำ 1 ชั่วโมง",
        "tr": "Alış ve iade arasında en az bir saat olması gerekir.",
        "vi": "Phải ít nhất 1 giờ trong Tương Lai",
        "zs": "取车和还车之间必须至少有1小时的时间差。",
        "zh": "取車和還車之間必須至少有1小時的時間差。"
    },
    "pickup": {
        "ar": "موقع استلام السيارة",
        "bg": "Мястото за получаване",
        "cs": "místo vyzvednutí",
        "da": "Afhentnings Sted",
        "de": "Anmietstation",
        "en": "Pick up location",
        "de_at": "Anmietstation",
        "de_campers": "Anmietstation",
        "de_ch": "Anmietstation",
        "ee": "Võtmiskoht",
        "el": "Τοποθεσία παραλαβής",
        "en_sg": "Pickup Location",
        "en_vans": "Pickup Location",
        "es": "Lugar de recogida",
        "es_ct": "lloc de recollida",
        "es_vans": "Lugar de recogida",
        "fi": "Noutokohde",
        "fr": "Le lieu de prise en charge",
        "fr_ch_vola": "Veuillez spécifier l'endroit de prise en charge",
        "fr_vola": "Veuillez spécifier l'endroit de prise en charge",
        "he": "תחנת איסוף",
        "hr": "Lokacija preuzimanja automobila",
        "hr_rs": "Lokacija preuzimanja automobila",
        "hu": "Autófelvétel helye",
        "in_id": "Tempat pengambilan",
        "is": "Afhendingarstaður",
        "it": "Località del ritiro",
        "jp": "貸出する場所",
        "ko": "대여지역",
        "lt": "Automobilio paėmimo vieta",
        "lv": "Saņemšanas Vieta",
        "my": "Tempat Mengambil",
        "nl": "In welke plaats",
        "nl_be": "In welke plaats",
        "nl_campers": "Ophaallocatie",
        "no": "Avhentings sted",
        "ph": "Lokasyon ng pagsusunduan",
        "pl": "Lokalizacja Wypożyczenia",
        "pt": "Estação de levantamento",
        "pt_rc_br": "Local de retirada",
        "ro": "Locaţie Preluare",
        "rs": "Lokacija preuzimanja automobila",
        "ru": "Место получения",
        "uk": "Місце, де забираєте",
        "sk": "Oblasť vyzdvihnutia",
        "sl": "Lokacija prevzema",
        "sv": "Upphämtningsplats",
        "th": "สถานที่รับรถ",
        "tr": "Alış Yeri",
        "vi": "Vị Trí Lấy Xe",
        "zs": "取车地点",
        "zh": "取車地點",
        "zh_tw": "取車地點"
    }
}
