var exports = module.exports = {
    isoLanguage: "SE",
	pickUp: "Upphämtning",
	dropOff: "Avlämning",
    country: "Land",
    city: "Stad",
    loc: "Plats",
    title: "Bilhyra",
    emptySelect: "Välj",
    pickUpDate: "Upphämtningsdatum",
    pickUpTime: "Tid",
    dropOffTime: "Tid",
    dropOffDate: "Avlämningsdatum",
    driverAge: "Förarens ålder",
    search: "Sök",
    errorSelectCountry: "Land Krävs",
    errorSelectCity: "Stad Krävs",
    errorSelectLocation: "Plates Krävs",
    airportTranslation: "Airport",
    airportTranslationLANG: "Airport",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Downtown",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Train Station",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Terminal",
    allAreasTranslation: " (All areas)"
}
