var exports = module.exports = {
    isoLanguage: "PL",
	pickUp: "Odbiór",
	dropOff: "Zwrot",
    country: "Kraj",
    city: "Miasto",
    loc: "Lokalizacja",
    emptySelect: "Proszę wybierz",
    title: "Wyszukaj samochód na wynajem",
    pickUpDate: "Data Odbioru",
    pickUpTime: "Czas",
    dropOffDate: "Data zwrotu",
    dropOffTime: "Czas",
    driverAgeBetween: "Wiek kierowcy między 25 a 70 rokiem życia",
    driverAge: "Wiek kierowcy",
    search: "Szukaj",
    errorSelectCountry: "Country Required",
    errorSelectCity: "City Required",
    errorSelectLocation: "Location Required",
    airportTranslation: "Airport",
    airportTranslationLANG: "Lotnisko",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Centrum miasta",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Stacja Kolejowa",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Terminal",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Hotel",
    allAreasTranslation: " (All areas)"
}
