var exports = module.exports = {
    isoLanguage: "RS",
	pickUp: "Preuzimanje",
	dropOff: "Povratak",
    country: "Država",
    city: "Grad",
    loc: "Lokacija",
    emptySelect: "Molimo izaberite",
    title: "Рентал цар",
    pickUpDate: "Datum preuzimanja",
    pickUpTime: "Vreme",
    dropOffDate: "Datum povratka",
    dropOffTime: "Vreme",
    driverAgeBetween: "Vozač ima između 25 i 70 godina",
    driverAge: "Starosno doba vozača",
    search: "Traži",
    errorSelectCountry: "Tražena država",
    errorSelectCity: "Traženi grad",
    errorSelectLocation: "Tražena lokacija",
    airportTranslation: "Airport",
    airportTranslationLANG: "Aerodrom",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Centar grada",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Železnička stanica",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Terminal",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Hotel",
    allAreasTranslation: " (All areas)"
}
