var exports = module.exports = {
    isoLanguage: "ZH_CN",
	pickUp: "取車",
	dropOff: "還車",
    country: "國家",
    city: "城市",
    loc: "地點",
    emptySelect: "請選擇",
    title: "車輛租賃",
    pickUpDate: "取車日期",
    pickUpTime: "取車時間",
    dropOffDate: "還車日期",
    dropOffTime: "還車時間",
    driverAgeBetween: "駕駛人年齡",
    driverAge: "駕駛人年齡",
    search: "搜尋",
    errorSelectCountry: "請選擇國家",
    errorSelectCity: "請選擇城市",
    errorSelectLocation: "請選擇地點",
    airportTranslation: "Airport",
    airportTranslationLANG: "機場",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "市區",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "火車站",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "航廈樓",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Hotel",
    allAreasTranslation: " (All areas)"
}
