var exports = module.exports = {
    isoLanguage: " PT-BR",
	pickUp: "Retirada",
	dropOff: "Devolução",
    country: "País",
    city: "Cidade",
    loc: "Local",
    emptySelect: "Por favor selecione",
    title: "Aluguel de carro",
    pickUpDate: "Data de Retirada",
    pickUpTime: "Tempo",
    dropOffDate: "Data de Devolução",
    dropOffTime: "Tempo",
    driverAgeBetween: "Idade do Condutor",
    driverAge: "Idade do Condutor",
    search: "Pesquise",
    errorSelectCountry: "País Pedido",
    errorSelectCity: "Cidade Pedida",
    errorSelectLocation: "Local Pedido",
    airportTranslation: "Airport",
    airportTranslationLANG: "Aeroporto",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Centro",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Estação Ferroviária",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Terminal",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Hotel",
    allAreasTranslation: "(All areas)"
}
