var exports = module.exports = {
    isoLanguage: "BG",
	pickUp: "Получаване",
	dropOff: "Връщане",
    country: "Държава",
    city: "Град",
    loc: "Място",
    emptySelect: "Моля изберете",
    title: "Наем на автомобил",
    pickUpDate: "Дата на получаване",
    pickUpTime: "Час",
    dropOffDate: "Дата на връщане",
    dropOffTime: "Час",
    driverAgeBetween: "Възраст на шофьора",
    driverAge: "Възраст на шофьора",
    search: "Търси",
    errorSelectCountry: "Трябва да въведете държава",
    errorSelectCity: "Трябва да въведете град",
    errorSelectLocation: "Трябва да въведете място",
    airportTranslation: "Airport",
    airportTranslationLANG: "Летище",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Център",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Ж.П. Гара",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Терминал",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Xотел",
    allAreasTranslation: "(All areas)"
}
