var exports = module.exports = {
    isoLanguage: "ES",
	pickUp: "Retirar",
	dropOff: "Devolver",
    country: "País",
    city: "Ciudad",
    loc: "Lugar",
    emptySelect: "Por favor seleccione",
    title: "Alquiler de Coches",
    pickUpDate: "Día de Recogida",
    pickUpTime: "Hora",
    dropOffDate: "Día de devolución",
    dropOffTime: "Hora",
    driverAgeBetween: "Edad del Conductor",
    driverAge: "Edad del Conductor",
    search: "Buscar",
    errorSelectCountry: "País Requerido",
    errorSelectCity: "Ciudad Requerida",
    errorSelectLocation: "Lugar Requerido",
    airportTranslation: "Airport",
    airportTranslationLANG: "Aeropuert",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Centro",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Estación de Tren",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Terminal",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Hotel",
    allAreasTranslation: " (All areas)"
}
