var exports = module.exports = {
    isoLanguage: "HE",
	pickUp: "איסוף",
	dropOff: "תחנת החזרה",
    country: "מדינה",
    city: "עיר",
    loc: "מקום",
    emptySelect: "אנא בחר ",
    title: "השכרת רכב",
    pickUpDate: "תאריך איסוף",
    pickUpTime: "שעת איסוף",
    dropOffDate: "שעת איסוף",
    dropOffTime: "שעת החזרה",
    driverAgeBetween: "גיל הנהג בין 25-70",
    driverAge: "גיל הנהג",
    search: "חפש",
    errorSelectCountry: "עיר מבוקשת",
    errorSelectCity: "עיר מבוקשת",
    errorSelectLocation: "עיר מבוקשת",
    airportTranslation: "Airport",
    airportTranslationLANG: "שדה תעופה ",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "עיר",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "תחנת רכבת",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "תחנת רכבת",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "מלון",
    allAreasTranslation: " (All areas)"
}
