var exports = module.exports = {
    isoLanguage: "RO",
	pickUp: "Preluare",
	dropOff: "Predare",
    country: "Tara",
    city: "Oraş",
    loc: "Locaţie",
    emptySelect: "Selectati",
    title: "Inchiriere maşină",
    pickUpDate: "Data de preluare",
    pickUpTime: "Oră Preluare",
    dropOffDate: "Data Predare",
    dropOffTime: "Oră Predare",
    driverAgeBetween: "Vârsta soferului",
    driverAge: "Vârsta soferului",
    search: "Caută",
    errorSelectCountry: "Introduceti tara",
    errorSelectCity: "Introduceti orasul",
    errorSelectLocation: "Introduceti locatia",
    airportTranslation: "Airport",
    airportTranslationLANG: "Aeroport",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Centru",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Gara",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Terminal",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Hotel",
    allAreasTranslation: " (All areas)"
}
