var exports = module.exports = {
    isoLanguage: "en-IE",
	pickUp: "",
	dropOff: "",
    country: "Country",
    city: "City",
    loc: "Location",
    emptySelect: "Please Select ",
    title: "Car Rental",
    pickUpDate: "Pick Up Date",
    pickUpTime: "Pick Up Time",
    dropOffDate: "Drop Off Date",
    dropOffTime: "Drop Off Time",
    driverAgeBetween: "Driver aged between 25 – 70",
    driverAge: "Driver's age",
    search: "Search",
    errorSelectCountry: "Country Required",
    errorSelectCity: "City Required",
    errorSelectLocation: "Location Required ",
    airportTranslation: "Airport",
    airportTranslationLANG: "Airport",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Downtown",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Train Station",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Terminal",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Hotel",
    allAreasTranslation: " (All areas)"
}
