var exports = module.exports = {
    isoLanguage: "DE-CH",
	pickUp: "Abholung",
	dropOff: "Rückgabe",
    country: "Land",
    city: "Stadt",
    loc: "Standort",
    emptySelect: "Bitte Auswählen",
    title: "Mietwagen",
    pickUpDate: "Abholdatum",
    pickUpTime: "Zeit",
    dropOffDate: "Rückgabedatum",
    dropOffTime: "Zeit",
    driverAgeBetween: "Alter des Fahrers",
    driverAge: "Alter des Fahrers",
    search: "Suche",
    errorSelectCountry: "Land erforderlich",
    errorSelectCity: "Stadt erforderlich",
    errorSelectLocation: "Standort erforderlich",
    airportTranslation: "Airport",
    airportTranslationLANG: "Flughafen",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Stadtzentrum",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Bahnhof",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Terminal",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Hotel"
}
