var exports = module.exports = {
    isoLanguage: "CS-CZ",
	pickUp: "Vyzvednutí",
	dropOff: "Navrácení",
    country: "Země",
    city: "Město",
    loc: "Místo",
    emptySelect: "Prosím vyberte",
    title: "Pronájem Vozu",
    pickUpDate: "Datum vyzvednutí",
    pickUpTime: "Čas",
    dropOffDate: "Datum odevzdání",
    dropOffTime: "Čas",
    driverAgeBetween: "Řidiči ve věku 25 – 70",
    driverAge: "Věk řidiče",
    search: "Hledej",
    errorSelectCountry: "Vyberte zemi",
    errorSelectCity: "Vyberte město",
    errorSelectLocation: "Vyberte místo",
    airportTranslation: "Airport",
    airportTranslationLANG: "Letiště",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Centrum Mesta",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Železniční Stanice",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Terminál",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Hotel",
    allAreasTranslation: "(All areas)"
}
