var exports = module.exports = {
    isoLanguage: "RU",
	pickUp: "Получение",
	dropOff: "Возврат",
    country: "Страна",
    city: "Город",
    loc: "Место проката",
    emptySelect: "Выберете пожалуйста",
    title: "Искать автомобили напрокат",
    pickUpDate: "Дата получения",
    pickUpTime: "Время",
    dropOffDate: "Дата сдачи",
    dropOffTime: "Время",
    driverAgeBetween: "Driver aged between 25 – 70",
    driverAge: "Возраст водителя",
    search: "Поиск",
    errorSelectCountry: "Нужно выбрать страну",
    errorSelectCity: "Нужно выбрать город",
    errorSelectLocation: "Нужно выбрать место",
    airportTranslation: "Airport",
    airportTranslationLANG: "Аэропорт",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Центр Города",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Станция Метро",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Вокзал",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Oтель",
    allAreasTranslation: " (All areas)"
}
