var exports = module.exports = {
    isoLanguage: "HU",
	pickUp: "Felvétel",
	dropOff: "Autóleadás",
    country: "Ország",
    city: "Város",
    loc: "Helyszín",
    emptySelect: "Kérjük, válasszon",
    title: "Autó Bérlés",
    pickUpDate: "Felvétel dátuma",
    pickUpTime: "Időpont",
    dropOffDate: "Leadás dátuma",
    dropOffTime: "Időpont",
    driverAgeBetween: "25 – 70 év közötti vezető?",
    driverAge: "Vezető kora",
    search: "Keresés",
    errorSelectCountry: "Ország",
    errorSelectCity: "Város",
    errorSelectLocation: "Helyszín",
    airportTranslation: "Airport",
    airportTranslationLANG: "Repülőtér",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Belváros",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Pályaudvar",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Terminál",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Szállodai",
    allAreasTranslation: " (All areas)"
}
