var exports = module.exports = {
    isoLanguage: "TH",
	pickUp: "รับรถ",
	dropOff: "ส่งคืน",
    country: "ประเทศ",
    city: "เมือง",
    loc: "สถานที่",
    emptySelect: "กรุณาเลือก",
    title: "รถเช่า",
    pickUpDate: "วันที่รับรถ",
    pickUpTime: "เวลารับรถ",
    dropOffDate: "วันที่ส่งรถ",
    dropOffTime: "เวลาส่งรถ",
    driverAgeBetween: "อายุผู้ขับ",
    driverAge: "อายุผู้ขับ",
    search: "ค้นหา",
    errorSelectCountry: "กรุณาเลือกประเทศ",
    errorSelectCity: "กรุณาเลือกเมือง",
    errorSelectLocation: "กรุณาเลือกสถานที่",
    airportTranslation: "Airport",
    airportTranslationLANG: "สนามบิน",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "ในเมือง",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "สถานีรถไฟ",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "สถานีปลายทาง",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "โรงแรม",
    allAreasTranslation: " (All areas)"
}
