var exports = module.exports = {
    isoLanguage: "KO",
	pickUp: "대여정보",
	dropOff: "반납하기",
    country: "국가",
    city: "도시",
    loc: "지역",
    emptySelect: "선택하세요",
    title: "차량 대여",
    pickUpDate: "대여날짜",
    pickUpTime: "대여시간",
    dropOffDate: "반납날짜",
    dropOffTime: "반납시간",
    driverAgeBetween: "운전자 연령 만 25 – 70세?",
    driverAge: "운전자 연령",
    search: "검색",
    errorSelectCountry: "국가 기입 필수",
    errorSelectCity: "도시 기입 필수",
    errorSelectLocation: "지역 기입 필수",
    airportTranslation: "Airport",
    airportTranslationLANG: "공항",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "시내",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "기차역",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "터미널",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "호텔",
    allAreasTranslation: " (All areas)"
}
