var exports = module.exports = {
    isoLanguage: "NL",
	pickUp: "Ophalen",
	dropOff: "Inleveren",
    country: "Land",
    city: "Plaats",
    loc: "Locatie",
    emptySelect: "Kies hier",
    title: "Auto Huren",
    pickUpDate: "Ophaaldatum",
    pickUpTime: "Tijd",
    dropOffDate: "Aflever datum",
    dropOffTime: "Tijd",
    driverAgeBetween: "Leeftijd Bestuurde",
    driverAge: "Leeftijd Bestuurde",
    search: "Zoeken",
    errorSelectCountry: "Land Vereiste",
    errorSelectCity: "Plaats Vereiste",
    errorSelectLocation: "Locatie Verplicht",
    airportTranslation: "Airport",
    airportTranslationLANG: "Luchthaven",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Centrum",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Treinstation",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Terminal",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Hotel",
    allAreasTranslation: " (All areas)"
}
