var exports = module.exports = {
    isoLanguage: "JA",
	pickUp: "貸出",
	dropOff: "返却",
    country: "国",
    city: "都市",
    loc: "営業所",
    emptySelect: "ご選択ください",
    title: "貸出",
    pickUpDate: "貸出日",
    pickUpTime: "返却日",
    dropOffDate: "返却日",
    dropOffTime: "返却日",
    driverAgeBetween: "ドライバーの年齢",
    driverAge: "ドライバーの年齢",
    search: "検索",
    errorSelectCountry: "国をお選びください。",
    errorSelectCity: "都市をお選びください。",
    errorSelectLocation: "営業所をお選びください。",
    airportTranslation: "Airport",
    airportTranslationLANG: "空港",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "市内",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "駅",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "ターミナル",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "ホテル",
    allAreasTranslation: " (All areas)"
}
