var exports = module.exports = {
    isoLanguage: "NO",
	pickUp: "Avhenting",
	dropOff: "Levering",
    country: "Land",
    city: "By",
    loc: "Sted",
    emptySelect: "Välj",
    title: "Leiebil",
    pickUpDate: "Hentedato",
    pickUpTime: "Tid",
    dropOffDate: "Avleveringsdato:",
    dropOffTime: "Tid",
    driverAgeBetween: "Sjåførens alder",
    driverAge: "Sjåførens alder",
    search: "Sök",
    errorSelectCountry: "Land Krävs",
    errorSelectCity: "Stad Krävs",
    errorSelectLocation: "Plates Krävs",
    airportTranslation: "Airport",
    airportTranslationLANG: "Flyplass",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Sentrum",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Togstasjon",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Terminal",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Hotel",
    allAreasTranslation: " (All areas)"
}
