var exports = module.exports = {
    isoLanguage: "FI",
	pickUp: "Nouto",
	dropOff: "Palautus",
    country: "Maa",
    city: "Kaupunki",
    loc: "Sijainti",
    emptySelect: "Ole hyvä ja Valitse",
    title: "Autonvuokraus",
    pickUpDate: "Noutoajankohta",
    pickUpTime: "Aika",
    dropOffDate: "Palautusajankohta",
    dropOffTime: "Aika",
    driverAgeBetween: "Kuljettajan ikä",
    driverAge: "Kuljettajan ikä",
    search: "Valitse",
    errorSelectCountry: "Maa Pakollinen",
    errorSelectCity: "Kaupunki Pakollinen",
    errorSelectLocation: "Paikkakunta Pakollinen",
    airportTranslation: "Airport",
    airportTranslationLANG: "Lentokenttä",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Keskusta",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Junaasema",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Terminaali",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Hotel",
    allAreasTranslation: " (All areas)"
}
