var exports = module.exports = {
    isoLanguage: "FR",
	pickUp: "Prise en charge",
	dropOff: "Restitution",
    country: "Pays",
    city: "Ville",
    loc: "Lieu",
    emptySelect: "Veuillez sélectionner",
    title: "Location de voiture",
    pickUpDate: "Date de prise en charge",
    pickUpTime: "Heure",
    dropOffDate: "Date de restitution",
    dropOffTime: "Heure",
    driverAgeBetween: "Age du conducteur",
    driverAge: "Age du conducteur",
    search: "Rechercher",
    errorSelectCountry: "Pays de prise en charge",
    errorSelectCity: "Ville de prise en charge",
    errorSelectLocation: "Lieu de prise en charge",
    airportTranslation: "Airport",
    airportTranslationLANG: "Aéroport",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Centre-ville",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Gare",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Terminal",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Hôtel",
    allAreasTranslation: " (All areas)"
}
