var exports = module.exports = {
    isoLanguage: "GR",
	pickUp: "Παραλαβή",
	dropOff: "Επιστροφή",
    country: "Χώρα",
    city: "Πόλη",
    loc: "Τοποθεσία",
    emptySelect: "Επιλογή",
    title: "Eνοικίαση αυτοκινήτων",
    pickUpDate: "Ημερομηνία παραλαβής",
    pickUpTime: "Ώρα παραλαβής",
    dropOffDate: "Ημερομηνία επιστροφής",
    dropOffTime: "Ώρα επιστροφής",
    driverAgeBetween: "Ηλικία οδηγού",
    driverAge: "Ηλικία οδηγού",
    search: "Αναζήτηση",
    errorSelectCountry: "Χώρα απαιτείται",
    errorSelectCity: "Πόλη απαιτείται",
    errorSelectLocation: "Τοποθεσία απαιτείται",
    airportTranslation: "Airport",
    airportTranslationLANG: "Αεροδρόμιο",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Κέντρο Πόλης",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Σταθμός τραίνων",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Τερματικός Σταθμός",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Hotel",
    allAreasTranslation: " (All areas)"
}
