var exports = module.exports = {
    isoLanguage: "HR",
	pickUp: "Preuzimanje",
	dropOff: "Povratak",
    country: "Država",
    city: "Grad",
    loc: "Lokacija",
    emptySelect: "Molimo odaberite",
    title: "Najam auta",
    pickUpDate: "Datum preuzimanja",
    pickUpTime: "Vrijeme",
    dropOffDate: "Datum povratka",
    dropOffTime: "Vrijeme",
    driverAgeBetween: "Vozač ima između 25 i 70 godina?",
    driverAge: "Starosna dob vozača",
    search: "Traži",
    errorSelectCountry: "Država potreban",
    errorSelectCity: "Grad potreban",
    errorSelectLocation: "Lokacija potreban",
    airportTranslation: "Airport",
    airportTranslationLANG: "Zračna Luka",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Centar",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Kolodvor",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Terminal",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Hotel",
    allAreasTranslation: " (All areas)"
}
