var exports = module.exports = {
    isoLanguage: "IT",
	pickUp: "Ritiro",
	dropOff: "Riconsegna",
    country: "Paese",
    city: "Cittá",
    loc: "Localitá",
    emptySelect: "Si prega di selezionare",
    title: "Noleggio Auto",
    pickUpDate: "Data Ritiro",
    pickUpTime: "Orario",
    dropOffDate: "Data Riconsegna",
    dropOffTime: "Orario",
    driverAgeBetween: "Driver aged between 25 – 70",
    driverAge: "Etá del conducente",
    search: "Cerca",
    errorSelectCountry: "Paese desiderato",
    errorSelectCity: "Cittá desiderata",
    errorSelectLocation: "Localitá desiderata",
    airportTranslation: "Airport",
    airportTranslationLANG: "Aeroporto",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Centro",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Stazione ferroviaria",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Terminal",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Hotel",
    allAreasTranslation: " (All areas)"
}
