var exports = module.exports = {
    isoLanguage: "ID",
	pickUp: "Pengambilan",
	dropOff: "Pengembalian",
    country: "Negara",
    city: "Kota",
    loc: "Lokasi",
    emptySelect: "Silahkan Pilih",
    title: "Cari penyewaan mobil",
    pickUpDate: "Tanggal pengambilan",
    pickUpTime: "Tanggal Pengembalian",
    dropOffDate: "Waktu",
    dropOffTime: "Waktu",
    driverAgeBetween: "Pengemudi berumur 25-70",
    driverAge: "Sopir usia ?",
    search: "Cari",
    errorSelectCountry: "negara Diperlukan",
    errorSelectCity: "Kota Diperlukan",
    errorSelectLocation: "Lokasi Diperlukan",
    airportTranslation: "Airport",
    airportTranslationLANG: "Bandar Udara",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Pusat kota",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Stasiun Kereta",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Terminal",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Hotel",
    allAreasTranslation: " (All areas)"
}
