var exports = module.exports = {
    isoLanguage: "AR",
	pickUp: "الاستلام",
	dropOff: "اعادة السيارة إلى",
    country: "البلد",
    city: "المدينة",
    loc: "موقع",
    emptySelect: "اختر من فضلك",
    title: "ايجار السيارات",
    pickUpDate: "تاريخ الإستلام",
    pickUpTime: "معاد الإستلام",
    dropOffDate: "تاريخ التسليم",
    dropOffTime: "معاد التسليم",
    driverAgeBetween: "سن السائق",
    driverAge: "سن السائق",
    search: "ابحث",
    errorSelectCountry: "البلد المطلوب",
    errorSelectCity: "لمدينة المطلوبة",
    errorSelectLocation: "الموقع المطلوب",
    airportTranslation: "Airport",
    airportTranslationLANG: "المطار",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "وسط البلد",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "محطة القطار",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "المبنى",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "فندق",
    allAreasTranslation: "(All areas)"
}
