var exports = module.exports = {
    isoLanguage: "LV",
	pickUp: "Saņemšana",
	dropOff: "Atgriešana",
    country: "Valsts",
    city: "Pilsēta",
    loc: "Vieta",
    emptySelect: "Lūdzu izvēlēties",
    title: "Auto Noma",
    pickUpDate: "Saņemšanas datums",
    pickUpTime: "Laiks",
    dropOffDate: "Nodošanas datums",
    dropOffTime: "Laiks",
    driverAgeBetween: "Vai vadītāja vecums ir starp 25-70 gadiem",
    driverAge: "Vadītāja vecums",
    search: "Meklēt",
    errorSelectCountry: "Country Required",
    errorSelectCity: "City Required",
    errorSelectLocation: "Location Required",
    airportTranslation: "Airport",
    airportTranslationLANG: "Lidosta",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Centrālā daļa",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Dzelzceļa Stacija",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Terminal",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Viesnīcas piegāde",
    allAreasTranslation: " (All areas)"
}
