var exports = module.exports = {
    isoLanguage: "UK",
	pickUp: "Забрати автомобіль",
	dropOff: "Повернення",
    country: "Країна",
    city: "Місто",
    loc: "Місце",
    emptySelect: "Будь ласка, виберіть",
    title: "прокат автомобілів",
    pickUpDate: "Дата отримання",
    pickUpTime: "Час",
    dropOffDate: "Дата повернення",
    dropOffTime: "Час",
    driverAgeBetween: "Вік водія від 25 до 70 років",
    driverAge: "Вік водія",
    search: "Пошук",
    errorSelectCountry: "Країна пошуку",
    errorSelectCity: "Місто пошуку",
    errorSelectLocation: "Місце пошуку",
    airportTranslation: "Airport",
    airportTranslationLANG: "Аеропорт",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Центр міста",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Залізничний вокзал",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Термінал",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Готель",
    allAreasTranslation: " (All areas)"
}
