var exports = module.exports = {
    isoLanguage: "EN-GB",
	pickUp: "Pick up",
	dropOff: "Drop off",
    country: "Country",
    city: "City",
    loc: "Location",
    emptySelect: "Please Select",
    title: "Car Rentals",
    pickUpDate: "Pick Up Date",
    pickUpTime: "Time",
    dropOffDate: "Drop Off Date",
    dropOffTime: "Time",
    driverAgeBetween: "Driver aged between 25 – 70",
    driverAge: "Driver's age",
    search: "Search",
    errorSelectCountry: "Country Required",
    errorSelectCity: "City Required",
    errorSelectLocation: "Location Required",
    airportTranslation: "Airport",
    airportTranslationLANG: "Airport",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Downtown",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Train Station",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Terminal",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Hotel",
    allAreasTranslation: " (All areas)"
}
