var exports = module.exports = {
    isoLanguage: "TR",
	pickUp: "ALIŞ",
	dropOff: "İade Yeri",
    country: " Ülke",
    city: "Şehir",
    loc: "Lokasyon",
    emptySelect: "Lütfen Seçiniz",
    title: "Araç Kiralama",
    pickUpDate: "Teslim alis tarihi",
    pickUpTime: "Teslim alış saati",
    dropOffDate: " Teslim edis tarih",
    dropOffTime: " Teslim ediş saati",
    driverAgeBetween: " Sürücü 25-70 yaş arası mı?",
    driverAge: "Sürücü",
    search: " ara",
    errorSelectCountry: "Ülke gerekir",
    errorSelectCity: "Şehir gerekir",
    errorSelectLocation: "Lokasyon gerekir",
    airportTranslation: "Airport",
    airportTranslationLANG: "Airport",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Downtown",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Train Station",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Termnial",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Hotel",
    allAreasTranslation: " (All areas)"
}
