var exports = module.exports = {
    isoLanguage: "ZH_HK ",
	pickUp: "取车",
	dropOff: "还车",
    country: "国家",
    city: "城市",
    loc: "地点",
    emptySelect: "请选择",
    title: "车辆租赁",
    pickUpDate: "取车日期",
    pickUpTime: "取车时间",
    dropOffDate: "还车日期",
    dropOffTime: "还车时间",
    driverAgeBetween: "驾驶人年龄",
    driverAge: "驾驶人年龄",
    search: "搜索",
    errorSelectCountry: "请选择国家",
    errorSelectCity: "请选择城市",
    errorSelectLocation: "请选择地点",
    airportTranslation: "Airport",
    airportTranslationLANG: "机场",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "市区",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "火车站",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "航厦楼",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Hotel",
    allAreasTranslation: " (All areas)"
}
