var exports = module.exports = {
    isoLanguage: "DK",
	pickUp: "Afhentning",
	dropOff: "Aflevering",
    country: "land",
    city: "By",
    loc: "Sted",
    emptySelect: "Foretag valg",
    title: "Billeje",
    pickUpDate: "Afhentings dato",
    pickUpTime: "Tid",
    dropOffDate: "Afleverings dato",
    dropOffTime: "Tid",
    driverAgeBetween: "Chaufførens alder",
    driverAge: "Chaufførens alder",
    search: "Søg",
    errorSelectCountry: "Land Nødvendig",
    errorSelectCity: "By Nødvendig",
    errorSelectLocation: "Sted Nødvendig",
    airportTranslation: "Airport",
    airportTranslationLANG: "Lufthavn",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Centrum",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Hovedbanegård",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Terminal",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Hotel",
    allAreasTranslation: " (All areas)"
}
