var exports = module.exports = {
    isoLanguage: "LT",
	pickUp: "Paėmimas",
	dropOff: "Grąžinimas",
    country: "Šalis",
    city: "Miestas",
    loc: "Vieta",
    emptySelect: "Prašome pasirinkti",
    title: "Automobilių Nuoma",
    pickUpDate: "Paėmimo data",
    pickUpTime: "Laikas",
    dropOffDate: "Grąžinimo data",
    dropOffTime: "Laikas",
    driverAgeBetween: "Vairuotojo amžius tarp 25 -70",
    driverAge: "Vairuotojo amžius",
    search: "Ieškoti",
    errorSelectCountry: "Šalis Nepieciešamais",
    errorSelectCity: "Miestas Nepieciešamais",
    errorSelectLocation: "Vieta Nepieciešamais",
    airportTranslation: "Airport",
    airportTranslationLANG: "Lidosta",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Miesto Centras",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Geležinkelio Stotis",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Terminal",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Hotel",
    allAreasTranslation: " (All areas)"
}
