var exports = module.exports = {
    isoLanguage: "CA",
	pickUp: "Recollida",
	dropOff: "Devolucio",
    country: "País",
    city: "Ciutat",
    loc: "Localització",
    emptySelect: "Selecciona per favor ",
    title: "Lloguer de cotxes",
    pickUpDate: "Data de Recollida",
    pickUpTime: "Hora",
    dropOffDate: "Data de Devolució",
    dropOffTime: "Hora",
    driverAgeBetween: "25 – 70 Edat entre 25-70",
    driverAge: "Edat del conductor",
    search: "Cerca",
    errorSelectCountry: "País requerit",
    errorSelectCity: "Ciutat requerit",
    errorSelectLocation: "localització requerida",
    airportTranslation: "Airport",
    airportTranslationLANG: "Aeroport",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Centre Ciutat ",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Estació de Trens",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Terminal",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Hotel",
    allAreasTranslation: "(All areas)"
}
