var exports = module.exports = {
    isoLanguage: "SK",
	pickUp: "Vyzdvihnutie",
	dropOff: "Odovzdanie",
    country: "Štát",
    city: "Mesto",
    loc: "Miesto",
    emptySelect: "Prosím zvoľte",
    title: "Prenájom",
    pickUpDate: "Dátum vyzdvihnutie",
    pickUpTime: "Čas",
    dropOffDate: "Dátum odovzdania",
    dropOffTime: "Čas",
    driverAgeBetween: "Vek vodiča 25-70rokov",
    driverAge: "Vek vodiča",
    search: "Hľadaj",
    errorSelectCountry: "Country Required",
    errorSelectCity: "City Required",
    errorSelectLocation: "Location Required",
    airportTranslation: "Airport",
    airportTranslationLANG: "Letisko",
    downTownTranslation: "Downtown",
    downTownTranslationLANG: "Centrum Mesta",
    trainStationTranslation: "Train Station",
    trainStationTranslationLANG: "Železničná Stanica",
    terminalTranslation: "Terminal",
    terminalTranslationLANG: "Terminal",
    hotelTranslation: "Hotel",
    hotelTranslationLANG: "Hotelu",
    allAreasTranslation: " (All areas)"
}
